### ISSUE TITLE
Native app error

### ISSUE THREAD

**Issue by outlying** [schibsted/sdk-android#12]
Seems like a bug in native app:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.spid.android.example.nativeapp/com.spid.android.example.nativeapp.MainActivity}: java.lang.IllegalStateException: SPiDEnvironment not set
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5274)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
     Caused by: java.lang.IllegalStateException: SPiDEnvironment not set
            at com.spid.android.sdk.configuration.SPiDConfigurationBuilder.build(SPiDConfigurationBuilder.java:203)
            at com.spid.android.example.nativeapp.MainActivity.onCreate(MainActivity.java:40)
            at android.app.Activity.performCreate(Activity.java:5977)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5274)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by oskarh** [comment]
Looks like you didn't specify which SPiDEnvironment you wanted to run when instantiating your SPiDConfiguration. These enums are in SPiDEnvironment, Norwegian or Swedish, stage or production.

An example for Norwegian stage would look like this:

    SPiDConfiguration config = new SPiDConfigurationBuilder(getApplicationContext(),
                SPiDEnvironment.NORWEGIAN_STAGE,
                "client-id", "client-secret", "url-scheme")
                .build();
    SPiDClient.getInstance().configure(config);
