### ISSUE TITLE
Problem with login, NullPointerException inside SPiDAccessToken class

### ISSUE THREAD

**Issue by outlying** [schibsted/sdk-android#14]
For some reason this exception is not handled, happen on NORWEGIAN_STAGED env with both valid and invalid credentials, earlier this week everything was OK

    FATAL EXCEPTION: main
    Process: no.vg.vgtv.debug, PID: 3985
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
        at com.spid.android.sdk.accesstoken.SPiDAccessToken.<init>(SPiDAccessToken.java:32)
        at com.spid.android.sdk.request.SPiDTokenRequest.doOnPostExecute(SPiDTokenRequest.java:42)
        at com.spid.android.sdk.request.SPiDRequest.onPostExecute(SPiDRequest.java:247)
        at com.spid.android.sdk.request.SPiDRequest.onPostExecute(SPiDRequest.java:35)
        at android.os.AsyncTask.finish(AsyncTask.java:632)
        at android.os.AsyncTask.access$600(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5274)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by oskarh** [comment]
That's odd, haven't seen it before. But it's caught and handled in the 1.3.6 release I just built so use that and you'll be fine.
